name: go test

on:
  [push]

jobs:
  install-go:
    runs-on: self-hosted
    steps:  
      - name: Setup Go Faster
        uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: '^1.18'
